version: '3'

volumes:
  checkerstate:

services:
  checker:
    build:
      context: ..
      dockerfile: checker2/Dockerfile
    command: localhost 1 ${TICK} # ip, team, tick
    network_mode: "host"
    volumes:
      - checkerstate:/tmp
